name: Backend-Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'maven'

      - name: Build with Maven
        run: cd ./carpooling-parent && mvn -Dmaven.test.skip=true -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker build
        id: buildX
        uses: docker/setup-buildx-action@v2

      - name: Build and push Gateway
        id: docker_build_gateway
        uses: docker/build-push-action@v4
        with:
          context: ./carpooling-gateway
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carpooling-gateway:latest

      - name: Build and push Auth
        id: docker_build_auth
        uses: docker/build-push-action@v4
        with:
          context: ./carpooling-auth
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carpooling-auth:latest

      - name: Build and push User
        id: docker_build_user
        uses: docker/build-push-action@v4
        with:
          context: ./carpooling-user/carpooling-user-api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carpooling-user-api:latest

      - name: Build and push Carpooling
        id: docker_build_carpooling
        uses: docker/build-push-action@v4
        with:
          context: ./carpooling-carpooling/carpooling-carpooling-api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carpooling-carpooling-api:latest

      - name: Build and push Order
        id: docker_build_order
        uses: docker/build-push-action@v4
        with:
          context: ./carpooling-order/carpooling-order-api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carpooling-order-api:latest

      - name: Build and push Payment
        id: docker_build_payment
        uses: docker/build-push-action@v4
        with:
          context: ./carpooling-payment/carpooling-payment-api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carpooling-payment-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: 传输docker-compose到服务器
        run: sshpass -p ${{secrets.REMOTE_PWD}} scp -r -o StrictHostKeyChecking=no ./docker-compose.yaml root@${{secrets.REMOTE_IP}}:/root/carpooling-server

      - name: 传输部署脚本到服务器
        run: sshpass -p ${{secrets.REMOTE_PWD}} scp -r -o StrictHostKeyChecking=no ./deploy.sh root@${{secrets.REMOTE_IP}}:/root/carpooling-server

      - name: 授权并执行部署脚本
        run: sshpass -p ${{secrets.REMOTE_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_IP}} "chmod +x /root/carpooling-server/deploy.sh && /root/carpooling-server/deploy.sh"
